//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivModTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CivModTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_BUILDING_{0}_{1}_DESC.
        /// </summary>
        internal static string key_building_desc {
            get {
                return ResourceManager.GetString("key_building_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_BUILDING_{0}_{1}_HELP.
        /// </summary>
        internal static string key_building_help {
            get {
                return ResourceManager.GetString("key_building_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_BUILDING_{0}_{1}_TEXT.
        /// </summary>
        internal static string key_building_pedia {
            get {
                return ResourceManager.GetString("key_building_pedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_BUILDING_{0}_{1}_STRATEGY.
        /// </summary>
        internal static string key_building_strategy {
            get {
                return ResourceManager.GetString("key_building_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_{0}_CITY_NAME_{1}.
        /// </summary>
        internal static string key_city_name {
            get {
                return ResourceManager.GetString("key_city_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_ADJECTIVE.
        /// </summary>
        internal static string key_civ_adjective {
            get {
                return ResourceManager.GetString("key_civ_adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_DESC.
        /// </summary>
        internal static string key_civ_desc {
            get {
                return ResourceManager.GetString("key_civ_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_DESC_SHORT.
        /// </summary>
        internal static string key_civ_desc_short {
            get {
                return ResourceManager.GetString("key_civ_desc_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_DOM.
        /// </summary>
        internal static string key_civ_dom_text {
            get {
                return ResourceManager.GetString("key_civ_dom_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_PEDIA_HEADER1.
        /// </summary>
        internal static string key_civ_pedia_header {
            get {
                return ResourceManager.GetString("key_civ_pedia_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_CIV_{0}_PEDIA_TEXT1.
        /// </summary>
        internal static string key_civ_pedia_text {
            get {
                return ResourceManager.GetString("key_civ_pedia_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_LEADER_{0}.
        /// </summary>
        internal static string key_leader {
            get {
                return ResourceManager.GetString("key_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_LEADER_{0}_PEDIA.
        /// </summary>
        internal static string key_leader_pedia {
            get {
                return ResourceManager.GetString("key_leader_pedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_LEADER_{0}_PEDIA_TAG.
        /// </summary>
        internal static string key_leader_pedia_tag {
            get {
                return ResourceManager.GetString("key_leader_pedia_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_{0}_SPY_NAME_{1}.
        /// </summary>
        internal static string key_spy_name {
            get {
                return ResourceManager.GetString("key_spy_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_TRAIT_{0}.
        /// </summary>
        internal static string key_trait {
            get {
                return ResourceManager.GetString("key_trait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT_KEY_TRAIT_{0}_DESC.
        /// </summary>
        internal static string key_trait_desc {
            get {
                return ResourceManager.GetString("key_trait_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/CriticalFlaw/Civ5.ModTool/master/Update.xml.
        /// </summary>
        internal static string txt_app_update {
            get {
                return ResourceManager.GetString("txt_app_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILDING_{0}_{1}.
        /// </summary>
        internal static string txt_building {
            get {
                return ResourceManager.GetString("txt_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ART_DEF_BUILDING_{0}.
        /// </summary>
        internal static string txt_building_art_def {
            get {
                return ResourceManager.GetString("txt_building_art_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILDINGCLASS_{0}.
        /// </summary>
        internal static string txt_building_class {
            get {
                return ResourceManager.GetString("txt_building_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIVILIZATION_{0}.
        /// </summary>
        internal static string txt_civ {
            get {
                return ResourceManager.GetString("txt_civ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ART_DEF_CIVILIZATION_{0}.
        /// </summary>
        internal static string txt_civ_art_def {
            get {
                return ResourceManager.GetString("txt_civ_art_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTSTYLE_{0}.
        /// </summary>
        internal static string txt_civ_art_style {
            get {
                return ResourceManager.GetString("txt_civ_art_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIV_{0}_ALPHA_ATLAS.
        /// </summary>
        internal static string txt_civ_atlas_alpha {
            get {
                return ResourceManager.GetString("txt_civ_atlas_alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_AlphaAtlas_{1}.dds.
        /// </summary>
        internal static string txt_civ_atlas_alpha_file {
            get {
                return ResourceManager.GetString("txt_civ_atlas_alpha_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIV_{0}_ICON_ATLAS.
        /// </summary>
        internal static string txt_civ_atlas_icon {
            get {
                return ResourceManager.GetString("txt_civ_atlas_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_IconAtlas_{1}.dds.
        /// </summary>
        internal static string txt_civ_atlas_icon_file {
            get {
                return ResourceManager.GetString("txt_civ_atlas_icon_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERCOLOR_{0}.
        /// </summary>
        internal static string txt_civ_color {
            get {
                return ResourceManager.GetString("txt_civ_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERCOLOR_{0}_PRIMARY.
        /// </summary>
        internal static string txt_civ_color_primary {
            get {
                return ResourceManager.GetString("txt_civ_color_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERCOLOR_{0}_SECONDARY.
        /// </summary>
        internal static string txt_civ_color_secondary {
            get {
                return ResourceManager.GetString("txt_civ_color_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERCOLOR_{0}_TEXT.
        /// </summary>
        internal static string txt_civ_color_text {
            get {
                return ResourceManager.GetString("txt_civ_color_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_DOM.dds.
        /// </summary>
        internal static string txt_civ_dom_image {
            get {
                return ResourceManager.GetString("txt_civ_dom_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_MAP_512.dds.
        /// </summary>
        internal static string txt_civ_map {
            get {
                return ResourceManager.GetString("txt_civ_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERA_{0}.
        /// </summary>
        internal static string txt_era {
            get {
                return ResourceManager.GetString("txt_era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAVOR_{0}.
        /// </summary>
        internal static string txt_flavor {
            get {
                return ResourceManager.GetString("txt_flavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADER_{0}.
        /// </summary>
        internal static string txt_leader {
            get {
                return ResourceManager.GetString("txt_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_SCENE.xml.
        /// </summary>
        internal static string txt_leader_scene {
            get {
                return ResourceManager.GetString("txt_leader_scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAJOR_CIV_APPROACH_{0}.
        /// </summary>
        internal static string txt_major_approach {
            get {
                return ResourceManager.GetString("txt_major_approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINOR_CIV_APPROACH_{0}.
        /// </summary>
        internal static string txt_minor_approach {
            get {
                return ResourceManager.GetString("txt_minor_approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\\XML\\{1}.xml.
        /// </summary>
        internal static string txt_output {
            get {
                return ResourceManager.GetString("txt_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELIGION_{0}.
        /// </summary>
        internal static string txt_religion {
            get {
                return ResourceManager.GetString("txt_religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_{0}.
        /// </summary>
        internal static string txt_resource {
            get {
                return ResourceManager.GetString("txt_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIALIST_{0}.
        /// </summary>
        internal static string txt_specialist {
            get {
                return ResourceManager.GetString("txt_specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECH_{0}.
        /// </summary>
        internal static string txt_tech {
            get {
                return ResourceManager.GetString("txt_tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAIT_{0}.
        /// </summary>
        internal static string txt_trait {
            get {
                return ResourceManager.GetString("txt_trait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITAI_{0}.
        /// </summary>
        internal static string txt_unit_ai {
            get {
                return ResourceManager.GetString("txt_unit_ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITCLASS_{0}.
        /// </summary>
        internal static string txt_unit_class {
            get {
                return ResourceManager.GetString("txt_unit_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YIELD_{0}.
        /// </summary>
        internal static string txt_yield {
            get {
                return ResourceManager.GetString("txt_yield", resourceCulture);
            }
        }
    }
}
