namespace CivModTool.Resources
{
    public enum Civs
    {
        America,
        Arabia,
        Assyria,
        Austria,
        Aztec,
        Babylon,
        Brazil,
        Byzantium,
        Carthage,
        Celts,
        China,
        Denmark,
        Egypt,
        England,
        Ethiopia,
        France,
        Germany,
        Greece,
        Huns,
        Inca,
        India,
        Indonesia,
        Iroquois,
        Japan,
        Korea,
        Maya,
        Mongol,
        Morocco,
        Netherlands,
        Ottoman,
        Persia,
        Poland,
        Polynesia,
        Portugal,
        Rome,
        Russia,
        Shoshone,
        Siam,
        Songhai,
        Spain,
        Sweden,
        Venice,
        Zulu
    }

    public enum ArtStyles
    {
        African,
        American,
        Asian,
        European,
        Mediterranean
    }

    public enum FileCategories
    {
        Buildings,
        Civilization,
        GameText,
        IconAtlas,
        Leader,
        PlayerColor,
        Trait,
        Units
    }

    public enum Religions
    {
        Buddhism,
        Christianity,
        Hinduism,
        Islam,
        Polytheism,
        Shintoism,
        Spiritualism,
        Zoroastrianism
    }

    public enum Eras
    {
        Ancient,
        Classical,
        Medieval,
        Renaissance,
        Industrial,
        Modern,
        Atomic,
        Information
    }

    public enum ResourceList
    {
        Aluminum,
        Bananas,
        Coal,
        Cotton,
        Cows,
        Deer,
        Dyes,
        Fish,
        Furs,
        Gems,
        Gold,
        Horses,
        Incense,
        Iron,
        Ivory,
        Marble,
        Oil,
        Pearls,
        Sheep,
        Silk,
        Silver,
        Spices,
        Stones,
        Sugar,
        Uranium,
        Whales,
        Wheat,
        Wine
    }

    public enum Yields // TO-DO: Complete the list
    {
        Gold,
        Science
    }

    public enum Buildings
    {
        // Unique
        Bazaar,

        BurialTomb,
        Courthouse,
        FloatingGardens,
        Krepost,
        Longhouse,
        MudPyramidMosque,
        MughalFort,
        PaperMaker,
        SatrapsCourt,
        Wat,

        // Special
        Forge,

        Garden,
        HydroPlant,
        Mint,
        Monastery,
        Observatory,
        Seaport,
        SolarPlant,
        Stable,
        Watermill,
        Windmill,
        Circus,

        // Normal
        Aqueduct,

        Armory,
        Arsenal,
        Bank,
        Barracks,
        BroadcastingTower,
        Castle,
        Colosseum,
        Factory,
        Granary,
        Harbor,
        Hospital,
        Laboratory,
        Library,
        Lighthouse,
        Market,
        MedicalLab,
        MilitaryAcademy,
        MilitaryBase,
        Monument,
        Museum,
        NuclearPlant,
        OperaHouse,
        PublicSchool,
        SpaceshipFactory,
        Stadium,
        StockExchange,
        StoneWorks,
        Temple,
        Theatre,
        University,
        Walls,
        Workshop,

        // National Wonders
        CircusMaximus,

        Hermitage,
        HeroicEpic,
        Ironworks,
        NationalCollege,
        NationalEpic,
        NationalTreasury,
        OxfordUniversity,
        Palace,

        // Wonders
        AngkorWat,

        BigBen,
        BrandenburgGate,
        ChichenItza,
        Colossus,
        CristoRedentor,
        EiffelTower,
        ForbiddenPalace,
        GreatLibrary,
        GreatLighthouse,
        GreatWall,
        HagiaSophia,
        HangingGarden,
        HimejiCastle,
        Kremlin,
        Louvre,
        MachuPichu,
        NotreDam,
        Oracle,
        Pentagon,
        PorcelainTower,
        Pyramid,
        SistineChapel,
        StatueOfLiberty,
        Stonehenge,
        SydneyOperaHouse,
        TajMahal,
        UnitedNations
    }

    public enum Technologies
    {
        Agriculture,
        Pottery,
        AnimalHusbandry,
        Archery,
        Mining,
        Sailing,
        Calendar,
        Writing,
        Trapping,
        TheWheel,
        Masonry,
        BronzeWorking,
        Optics,
        Philosophy,
        HorsebackRiding,
        Mathematics,
        Construction,
        IronWorking,
        Theology,
        CivilService,
        Currency,
        Engineering,
        MetalCasting,
        Compass,
        Education,
        Chivalry,
        Machinery,
        Physics,
        Steel,
        Astronomy,
        Acoustics,
        Banking,
        PrintingPress,
        Gunpowder,
        Navigation,
        Economics,
        Chemistry,
        Metallurgy,
        Archaeology,
        ScientificTheory,
        MilitaryScience,
        Fertilizer,
        Rifling,
        Biology,
        SteamPower,
        Electricity,
        ReplaceableParts,
        Railroad,
        Dynamite,
        Refrigeration,
        Telegraph,
        Radio,
        Flight,
        Combustion,
        Plastic,
        Penicilin,
        Electronics,
        MassMedia,
        Radar,
        AtomicTheory,
        Ecology,
        Computers,
        Rocketry,
        Lasers,
        NuclearFission,
        Globalization,
        Robotics,
        Satellites,
        Stealth,
        AdvancedBallistics,
        ParticlePhysics,
        Nanotechnology,
        FutureTech
    }

    public enum Units
    {
        AntiAircraftGun,
        AntiTankGun,
        Archer,
        Artillery,
        AtomicBomb,
        Battleship,
        Bomber,
        Bomber_B17,
        Cannon,
        Caravel,
        Carrier,
        Catapult,
        Catapult_Ballista,
        Cavalry,
        Cavalry_Cossack,
        ChariotArcher,
        ChariotArcher_WarChariot,
        ChariotArcher_Warelephant,
        Crossbowman,
        Crossbowman_Chukonu,
        Crossbowman_Longbowman,
        Destroyer,
        Fighter,
        Fighter_JapaneseZero,
        Frigate,
        Frigate_ShipOfTheLine,
        Galley,
        GuidedMissle,
        HelicopterGunship,
        Horseman,
        Horseman_CompanionCavalry,
        Infantry,
        Infantry_ForeignLegion,
        Ironclad,
        JetFighter,
        Knight,
        Knight_Camelarcher,
        Knight_MuslimCavalry,
        Knight_Warelephant,
        Lancer,
        Lancer_Sipahi,
        Longswordman,
        Longswordman_Samurai,
        Mech,
        MechanizedInfantry,
        MissleCruiser,
        MobileSAM,
        ModernArmor,
        Musketman,
        Musketman_Janissary,
        Musketman_Minuteman,
        Musketman_Musketeer,
        NuclearMissle,
        NuclearSubmarine,
        Paratrooper,
        Pikeman,
        Pikeman_Landsknecht,
        Rifleman,
        RocketArtillery,
        Scout,
        Settler,
        Spearman,
        Spearman_Hoplite,
        Spearman_Immortal,
        StealthBomber,
        Submarine,
        Swordman,
        Swordman_Legion,
        Swordman_MohawkWarrior,
        Tank,
        Tank_Panzer,
        Trebuchet,
        Trireme,
        Warrior,
        Warrior_Jaguar,
        Workboat,
        Worker,

        // Barbarians
        Barbarian_Archer,

        Barbarian_Spearman,
        Barbarian_Swordman,
        Barbarian_Warrior,

        // SpaceShip
        SpaceShip_Booster,

        SpaceShip_Cockpit,
        SpaceShip_Engine,
        SpaceShip_StasisChamber,

        // Great Person
        Artist,

        Engineer,
        General,
        Merchant,
        Scientist
    }

    public enum AiTypes
    {
        Unknown,
        Settle,
        Worker,
        Attack,
        City_Bombard,
        Fast_Attack,
        Defense,
        Counter,
        Ranged,
        City_Special,
        Explore,
        Artist,
        Scientist,
        General,
        Merchant,
        Engineer,
        ICBM,
        Worker_Sea,
        Attack_Sea,
        Reserve_Sea,
        Escort_Sea,
        Explore_Sea,
        Assault_Sea,
        Settler_Sea,
        Carrier_Sea,
        Missle_Carrier_Sea,
        Pirate_Sea,
        Attack_Air,
        Defense_Air,
        Carrier_Air,
        Missle_Air,
        Paradrop,
        Spaceship_Part,
        Treasure,
        Prophet,
        Missionary,
        Inquisitor,
        Admiral
    }

    public enum MajorBiases
    {
        War,
        Hostile,
        Deceptive,
        Guarded,
        Afraid,
        Friendly,
        Neutral
    }

    public enum MinorBiases
    {
        Ignore,
        Friendly,
        Protective,
        Conquest
    }

    public enum Flavors
    {
        Offense,
        Defense,
        Military_Training,
        Recon,
        Ranged,
        Mobile,
        Naval,
        Naval_Recon,
        Naval_Growth,
        Naval_Tile_Improvement,
        Air,
        Expansion,
        Growth,
        Tile_Improvement,
        Infrastructure,
        Production,
        Gold,
        Science,
        Culture,
        Happiness,
        Great_People,
        Wonder,
        Religion,
        Diplomacy,
        Spaceship,
        Water_Connection,
        Nuke,
        Use_Nuke,
        Air_Carrier

    }
}